GET http://localhost:5000/cars

### 

GET http://localhost:5000/cars/4

### 
POST http://localhost:5000/cars
Content-Type: application/json

{
    "name" : "Porchse 1992",
    "brand" : "Porchse",
    "type" : "Mobil sport",
    "condition" : 2
}

### 
PUT http://localhost:5000/cars/2
Content-Type: application/json

{
    "name" : "Ninja",
    "brand" : "Kiwisiki",
    "type" : "motor trail"
}

### 
DELETE  http://localhost:5000/cars/3